version: '2'
services:
  app:
    image: php:7-apache
    tty: true
    stdin_open: true
    volumes_from:
    - app-data
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: app-data
  app-data:
    image: emarref/hello-world
    tty: true
    stdin_open: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
