version: '2'
services:
  hello-world-lb:
    ports:
    - 80
    image: rancher/lb-service-haproxy
  app:
    image: php:7-apache
    tty: true
    stdin_open: true
    ports:
    - "${public_port}:80"
    volumes_from:
    - app-data
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: app-data
  app-data:
    image: emarref/hello-world
    tty: true
    stdin_open: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
